// <auto-generated />
using System;
using DigitArenaBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitArenaMiner.Migrations
{
    [DbContext(typeof(DefaultDatabaseContext))]
    partial class DefaultDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitArenaBot.Models.ArchivedMessages", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("ArchivedMessages");
                });

            modelBuilder.Entity("DigitArenaBot.Models.CumRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("CumRecords");
                });

            modelBuilder.Entity("DigitArenaBot.Models.MessageReactionCount", b =>
                {
                    b.Property<decimal>("IdMessage")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("EmoteIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<decimal>("IdSender")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("IdMessage", "EmoteIdentifier");

                    b.HasIndex("IdSender", "EmoteIdentifier");

                    b.ToTable("MessageReactionCounts");
                });

            modelBuilder.Entity("DigitArenaBot.Models.UserActionCount", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ActionName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ActionName");

                    b.HasIndex("UserId", "ActionName");

                    b.ToTable("UserActionCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
